Create diagram
Ivan-Veselov/sql-homework pull request #1
Opened 2017-09-15 14:22 UTC by Ivan-Veselov

Посмотрите на текущую диаграмму таблиц. Аня, так как ты не обсуждала с нами структуру базы данных, то тебе в особенности нужно разобраться с тем, что мы там напридумывали, задавай вопросы.

2017-09-15 16:54 UTC, shavkunov requested changes

2017-09-15 16:54 UTC, shavkunov commented on diagram.xml
> +<mxfile userAgent="Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" version="7.3.9" editor="www.draw.io" type="device"><diagram id="
А может стоило ещё типы добавить к полям?
Просто когда нужно будет писать запрос, сразу видно что за тип и не вспоминать каждый раз.

2017-09-15 17:10 UTC, Ivan-Veselov commented on diagram.xml
> +<mxfile userAgent="Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" version="7.3.9" editor="www.draw.io" type="device"><diagram id="
Это правда. Но, поскольку ты будешь писать создание таблиц, а мы не обсудили типы, то давай сделаем это за две итерации. Сначала ты напишешь код, мы его посмотрим, а потом я (ну или ещё кто) проставлю типы в диаграмме.

2017-09-15 22:28 UTC, demarkok requested changes
1) Почему сущность, связывающая атлета и соревнование, называется Competitor? 
2) Имена сущностей на диаграмме - это не имена таблиц? В противном случае, возможно, стоит называть их во множественном числе?

2017-09-15 22:59 UTC, demarkok submitted a review, later dismissed

2017-09-17 10:05 UTC, shavkunov requested changes

2017-09-17 10:05 UTC, shavkunov commented on diagram.xml
> +<mxfile userAgent="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0" version="7.3.9" editor="www.draw.io" type="github"><diagram id="eb2ec0fc-0f2d-9a1c-a81c-d80df860849d"
Need to specify enums in diagrams

2017-09-17 10:28 UTC, Fedannie submitted a review, later dismissed

2017-09-17 13:25 UTC, Fedannie approved these changes

2017-09-17 17:11 UTC, demarkok approved these changes

2017-09-17 17:12 UTC, shavkunov approved these changes

2017-09-17 17:24 UTC, merged