Generation
Ivan-Veselov/sql-homework pull request #20
Opened 2017-12-12 09:03 UTC by demarkok

Data generation and database deployment script were added.

2017-12-12 10:24 UTC, demarkok commented
fixes #15
fixes #16

2017-12-13 08:09 UTC, Ivan-Veselov commented
fixes нужно в самом описании к PR писать.

2017-12-13 08:29 UTC, Ivan-Veselov requested changes
Предлагаю вынести внешний порт в аргумент скрипта.

2017-12-14 10:19 UTC, demarkok commented
@Ivan-Veselov  Вынес (дефолтный при этом 5432).

2017-12-14 11:04 UTC, Ivan-Veselov submitted a review, later dismissed

2017-12-14 11:07 UTC, Ivan-Veselov approved these changes

2017-12-14 11:07 UTC, merged